# Generated by Django 5.2 on 2025-11-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roasted_app', '0004_order_rating_order_review_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
    ]
