# Generated by Django 5.2 on 2025-11-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasted_app', '0005_remove_customer_loyalty_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcash_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='gcash_qr/')),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'GCash Settings',
                'verbose_name_plural': 'GCash Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('waiting_payment', 'Waiting for Payment'), ('for_verification', 'For Verification'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', max_length=20),
        ),
    ]
